"""播客场景预设配置"""
# 预设格式: name -> {voice_id, style, speed, emotion, global_instruction}
# 用户选择预设后，自动填充到主播配置和全局指令中

SCENE_PRESETS = {
    "📖 讲故事": {
        "description": "生动有代入感的故事讲述",
        "voice_id": "冰糖",
        "style": "叙述",
        "speed": "正常",
        "emotion": "平静",
        "global_instruction": "讲故事场景，有代入感、有感染力，自然停顿，像在给朋友讲故事",
    },
    "🎓 知识分享": {
        "description": "清晰专业的知识讲解",
        "voice_id": "苏打",
        "style": "平静",
        "speed": "正常",
        "emotion": "专注",
        "global_instruction": "知识分享场景，吐字清晰，重点突出，像老师在讲课，通俗易懂",
    },
    "📰 新闻播报": {
        "description": "专业客观的新闻播报",
        "voice_id": "茉莉",
        "style": "新闻播报",
        "speed": "偏快",
        "emotion": "严肃",
        "global_instruction": "新闻播报场景，语速均匀，吐字清晰，语气客观正式，不带个人情绪",
    },
    "💬 深度访谈": {
        "description": "自然流畅的访谈对话",
        "voice_id": "冰糖",
        "style": "平静",
        "speed": "正常",
        "emotion": "沉稳",
        "global_instruction": "访谈对话场景，口语化，自然停顿，像朋友聊天，减少播音腔",
    },
    "👶 亲子故事": {
        "description": "温柔亲切的儿童内容",
        "voice_id": "冰糖",
        "style": "温柔",
        "speed": "偏慢",
        "emotion": "温柔",
        "global_instruction": "讲给孩子听，声音轻柔温暖，语速慢，有亲和力，像妈妈在哄睡",
    },
    "🔍 悬疑讲述": {
        "description": "紧张神秘的悬疑氛围",
        "voice_id": "白桦",
        "style": "紧张",
        "speed": "偏慢",
        "emotion": "紧张",
        "global_instruction": "悬疑讲述场景，营造紧张氛围，语速慢，有神秘感，让人屏住呼吸",
    },
    "💼 商业财经": {
        "description": "专业稳重的财经分析",
        "voice_id": "Dean",
        "style": "严肃",
        "speed": "正常",
        "emotion": "沉稳",
        "global_instruction": "商业财经场景，专业稳重，有权威感，数据清晰，逻辑严谨",
    },
    "💪 激情演讲": {
        "description": "富有感染力的演讲",
        "voice_id": "苏打",
        "style": "兴奋",
        "speed": "偏快",
        "emotion": "兴奋",
        "global_instruction": "演讲场景，充满激情，声音高亢，节奏感强，有号召力",
    },
    "🌙 睡前陪伴": {
        "description": "舒缓放松的睡前内容",
        "voice_id": "冰糖",
        "style": "温柔",
        "speed": "很慢",
        "emotion": "平静",
        "global_instruction": "睡前陪伴场景，语速非常慢，声音轻柔，像在耳边低语，让人放松入睡",
    },
    "😄 轻松闲聊": {
        "description": "轻松愉快的聊天氛围",
        "voice_id": "Mia",
        "style": "幽默",
        "speed": "偏快",
        "emotion": "开心",
        "global_instruction": "轻松闲聊场景，口语化，带着笑意，像朋友之间聊天，轻松愉快",
    },
    "📚 有声书": {
        "description": "专业有声书朗读",
        "voice_id": "白桦",
        "style": "叙述",
        "speed": "正常",
        "emotion": "平静",
        "global_instruction": "有声书朗读场景，叙述自然，情感适中，有画面感，像专业播音员",
    },
    "🏋️ 健康生活": {
        "description": "积极向上的健康内容",
        "voice_id": "苏打",
        "style": "平静",
        "speed": "正常",
        "emotion": "积极",
        "global_instruction": "健康生活场景，积极向上，通俗易懂，有亲和力，像朋友分享经验",
    },
}
